<?php

namespace AppBundle\Entity;

use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr as Expr;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function findAllArticles($id = null)
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->select('a, c, t')
            ->leftJoin('a.category', 'c', Expr\Join::WITH)
            ->leftJoin('a.tag', 't', Expr\Join::WITH)
            ->orderBy('a.id', 'ASC')
        ;

        if(null != $id){
            $qb
                ->where('a.id = :id')
                ->setParameters([
                    ':id' => $id,
                ])
            ;
        }

        return null === $id
            ? $qb->getQuery()->getArrayResult()
            : $qb->getQuery()->getSingleResult(AbstractQuery::HYDRATE_ARRAY)
            ;
    }
}
